//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collection()
        {
            this.Book_Collection = new HashSet<Book_Collection>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> Inkognito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Collection> Book_Collection { get; set; }
        public virtual User User { get; set; }
    }
}
